services:
  springboot:
    image: gpemvjtmxm/stuv-app:latest
    container_name: stuv-app
    restart: always
    env_file:
      - /home/ubuntu/env/.env
    environment:
      - TZ=Asia/Seoul

    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 3