auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 1m
  http_server_write_timeout: 1m
  grpc_server_max_send_msg_size: 2147483647
  grpc_server_max_recv_msg_size: 2147483647

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-03-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  per_stream_rate_limit: 256M
  ingestion_burst_size_mb: 500
  ingestion_rate_mb: 2000
  max_entries_limit_per_query: 500000
  max_global_streams_per_user: 1000

frontend:
  max_outstanding_per_tenant: 1024
  compress_responses: true

querier:
  max_concurrent: 512

query_scheduler:
  max_outstanding_requests_per_tenant: 1024
