global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'stuv-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['stuv-app:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
