name: CD

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: prod
    steps:
      - name: 브랜치 최신화
        uses: actions/checkout@v3

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 명령 실행을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle build 수행
        run: ./gradlew clean build

      - name: 도커 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker-compose 사용하여 이미지 빌드&push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker-compose -f docker-compose.yml build
          docker image tag stuv-app ${{ secrets.DOCKER_HUB_USERNAME }}/stuv-app
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/stuv-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # 해당 부분 검토 필요
    steps:
      - name: SSH로 EC2 접속
        uses: appleboy/ssh-action@v0.1.3
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ENV_VARS
          script: |
            cd /home/ubuntu/WEB2_3_Wooamo_BE
            sudo docker compose down
            sudo docker compose rm -f
            sudo docker compose pull
            echo "$ENV_VARS" > src/main/resources/.env
            sudo docker compose --env-file ./src/main/resources/.env up -d